from __future__ import annotations

from .ttfonts import TTFont


def registerFont(font: TTFont) -> None: ...
def stringWidth(text: str, fontName: str, fontSize: float) -> float: ...
def getAscent(fontName: str, fontSize: float | None = ...) -> float: ...
def getDescent(fontName: str, fontSize: float | None = ...) -> float: ...
