from __future__ import annotations

from typing import Any


class Canvas:
    def __init__(self, filename_or_buffer: Any, pagesize: tuple[float, float] | None = ...) -> None: ...
    def setFont(self, fontName: str, fontSize: float) -> None: ...
    def drawCentredString(self, x: float, y: float, text: str) -> None: ...
    def drawString(self, x: float, y: float, text: str) -> None: ...
    def line(self, x1: float, y1: float, x2: float, y2: float) -> None: ...
    def drawImage(
        self,
        image: Any,
        x: float,
        y: float,
        width: float | None = ...,
        height: float | None = ...,
        mask: Any | None = ...,
        preserveAspectRatio: bool = ...,
        anchor: str = ...,
        anchorAtXY: bool = ...,
        showBoundary: bool = ...,
        extraReturn: Any | None = ...,
    ) -> Any: ...
    def saveState(self) -> None: ...
    def restoreState(self) -> None: ...
    def setLineWidth(self, width: float) -> None: ...
    def rect(self, x: float, y: float, width: float, height: float) -> None: ...
    def showPage(self) -> None: ...
    def save(self) -> None: ...
